packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  "postcss@<8.5.10": ">=8.5.10"
  "esbuild@<0.25.0": ">=0.25.0"

patchedDependencies:
  "@react-email/editor@1.5.10": "patches/@react-email__editor@1.5.10.patch"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
