// next-env.d.ts (gitignored, generated by `next dev`/`next build`) is what normally loads
// these; CI typechecks without a build, so static image imports need them tracked here.
/// <reference types="next/image-types/global" />
